clamav: Update to version 1.5.1
-- Update from version 1.3.2 to 1.5.1
-- Change to rootfile
-- only build clamav for x86_64, not for loongarch64 since there is some
error related to rust:

   Compiling half v2.7.0
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /usr/src/clamav-1.5.1/.cargo/vendor/half/src/lib.rs:218:5
    |
218 | /     feature(
219 | |         stdarch_loongarch,
220 | |         stdarch_loongarch_feature_detection,
221 | |         loongarch_target_feature
222 | |     )
    | |_____^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `half` (lib) due to 1 previous error

Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>