linux-firmware: skip broken symbolic check in copy-firmware.sh
the symbolic check in copy-firmware.sh result in linux-firmware build
error like below, /etc/sound does not exist in build root
build_loongarch64. let's ignore the symbolic link check and delete the
broken symbolic link after linux-firmware installation.

====================================== Installing linux-firmware-20250211 ...
Install started; saving file list to /usr/src/lsalr ...
mkdir -p /lib/firmware
cd /usr/src/linux-firmware-20250211 && make install
make[1]: Entering directory '/usr/src/linux-firmware-20250211'
install -d /lib/firmware
./copy-firmware.sh -j1 /lib/firmware
ERROR: Broken symlinks found:\n/lib/firmware/turtlebeach/msndinit.bin
/lib/firmware/turtlebeach/msndperm.bin
/lib/firmware/turtlebeach/pndspini.bin
/lib/firmware/turtlebeach/pndsperm.bin

[root@fedora loongfire]# ls -l build_loongarch64/lib/firmware/turtlebeach/
total 64
lrwxrwxrwx 1 root root 23 Feb 17 07:33 msndinit.bin -> /etc/sound/msndinit.bin
lrwxrwxrwx 1 root root 23 Feb 17 07:33 msndperm.bin -> /etc/sound/msndperm.bin
lrwxrwxrwx 1 root root 23 Feb 17 07:33 pndsperm.bin -> /etc/sound/pndsperm.bin
lrwxrwxrwx 1 root root 23 Feb 17 07:33 pndspini.bin -> /etc/sound/pndspini.bin

[root@fedora loongfire]# ls -l build_loongarch64/etc/sound
ls: cannot access 'build_loongarch64/etc/sound': No such file or directory

Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>