Revert "protobuf: Update to version 33.0"
This reverts commit 678bcb85b17048b3edfb27d8f09f4e2442582ca6.

got many build error after updating to 33.0 like below:

/usr/src/protobuf-33.0/src/google/protobuf/wire_format.h:247:29: error: expected ';' at end of member declaration
  247 |   ABSL_DEPRECATE_AND_INLINE()
      |                             ^

Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>