net-tools: Disable ROSE protocol support for kernel 7.1.1+
The linux/rose.h header was removed from the Linux kernel in version
7.1.1+ as part of the AX.25/ROSE subsystem removal. This causes
net-tools 2.10 to fail building with:

  rose.c:41:10: fatal error: linux/rose.h: No such file or directory

Disable ROSE support in net-tools by setting HAVE_AFROSE and HAVE_HWROSE
to 0 in both config.h and config.make. The ROSE protocol is an obsolete
amateur radio stack that has been removed from the kernel and is not
used in LoongFire.

Assisted-by: Deepseek
Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>